#requires -Version 7.0
<#
.SYNOPSIS
    Generate the short slash-command alias files under .claude/commands/ from one table.

.DESCRIPTION
    Claude Code has NO native alias mechanism for a custom slash command: a command is
    addressed by its FILE NAME, and the `name:` frontmatter field is ignored in
    .claude/commands/*.md. A second invocable name therefore requires a second file.
    Hand-writing those files invites drift, so this script owns them: the table below is
    the single source of truth and every alias file is a render target of it.

    Three alias sets are emitted per canonical command, because the owner types in two
    keyboard layouts:

      Latin     - two letters, all `s`-prefixed (`/sd`). No built-in CLI command is that
                  short, so the namespace cannot collide.
      Translit  - the Latin alias written in Cyrillic (`/сд`), for reading as a Russian
                  abbreviation. Three letters have no natural Cyrillic twin and are
                  mapped by convention: q->й, c->ц, w->ш.
      Shadow    - the SAME PHYSICAL KEYS as the Latin alias, typed on the ЙЦУКЕН layout
                  (`/ыв`). This one is not about length: it makes the muscle memory work
                  without noticing which layout is active.

    Each generated file is a delegating driver, never a copy: it tells the model to invoke
    the canonical command and pass `$ARGUMENTS` through. The canonical file keeps the body,
    so nothing is duplicated and the alias costs ~8 lines.

    Every generated file carries `disable-model-invocation: true`. That keeps the alias
    typeable by the human while removing it from the model-facing skill listing, so 42
    alias files cost zero tokens per turn. Only the canonical commands stay model-invocable.

    Files are identified as generated by their `alias_of:` metadata key, which is what
    makes -Prune safe: a hand-written command file is never touched.

    Non-ASCII file names are NOT documented as supported by Claude Code. The Cyrillic sets
    are therefore an empirical bet: if the CLI does not route `/сд`, run -Prune -Sets latin
    to drop them without disturbing the Latin set.

    Exit codes:
      0 - success (files written, or -Check found no drift)
      1 - -Check found drift, or a write failed
      2 - could not verify: the repository layout is not where this script expects it,
          or a table row names a canonical command with no .claude/commands/<name>.md
#>
[CmdletBinding()]
param(
    # Emit only these sets. Default: all three.
    [ValidateSet('latin', 'translit', 'shadow')]
    [string[]] $Sets = @('latin', 'translit', 'shadow'),

    # Verify on-disk alias files match what the table would generate; write nothing.
    [switch] $Check,

    # Delete generated alias files that the requested table no longer produces.
    [switch] $Prune
)

. (Join-Path $PSScriptRoot '..\_profile.ps1')

$ErrorActionPreference = 'Stop'

$commandsDir = (Get-SzaPath 'commandsDir')

if (-not (Test-Path -LiteralPath $commandsDir)) {
    Write-Error "commands directory not found: $commandsDir" -ErrorAction Continue
    exit 2
}

# canonical command -> alias in each set.
# Selected from measured usage: transcript mining over the live window found these the
# commands actually typed by hand. Pipeline-internal commands invoked by other commands
# are deliberately absent - an alias nobody types is menu noise.
# S2402: the table is the project's (commands.aliases in the profile), one row per canonical
# command with a `canonical` key and one key per set name.
$aliasTable = @(
    foreach ($entry in @(Get-SzaProfileValue 'commands.aliases')) {
        $row = @{}
        foreach ($prop in $entry.PSObject.Properties) { $row[$prop.Name] = [string]$prop.Value }
        if (-not $row.ContainsKey('canonical') -or [string]::IsNullOrWhiteSpace($row['canonical'])) {
            Write-Error 'commands.aliases: every row needs a `canonical` command name.' -ErrorAction Continue
            exit 2
        }
        $row
    }
)
if ($aliasTable.Count -eq 0) {
    Write-Host 'generate-command-aliases: the profile declares no commands.aliases - nothing to generate.' -ForegroundColor DarkGray
    exit 0
}

function New-AliasBody {
    param(
        [Parameter(Mandatory)] [string] $Canonical,
        [Parameter(Mandatory)] [string] $Alias,
        [Parameter(Mandatory)] [string] $SetName
    )

    # Single-quoted here-string: $ARGUMENTS must reach the file literally, not expand here.
    $template = @'
---
description: "Alias -> /{CANONICAL}. Generated; edit commands.aliases in .sza-profile.json and regenerate."
argument-hint: "same arguments as /{CANONICAL}"
disable-model-invocation: true
metadata:
  alias_of: {CANONICAL}
  alias_set: {SET}
  generated_by: sza-harness aliases/generate-command-aliases.ps1
---

`/{ALIAS}` is a short alias for `/{CANONICAL}` and carries no behaviour of its own.

Invoke the Skill tool with skill `{CANONICAL}`, passing `$ARGUMENTS` as its args, and follow
that command exactly. Do nothing before that call and do not restate this file - the operator
typed a shortcut, not a new instruction.
'@

    return $template.Replace('{CANONICAL}', $Canonical).Replace('{ALIAS}', $Alias).Replace('{SET}', $SetName)
}

$expected = @{}
$ownerOf = @{}
foreach ($row in $aliasTable) {
    $canonicalFile = Join-Path $commandsDir "$($row.canonical).md"
    if (-not (Test-Path -LiteralPath $canonicalFile)) {
        Write-Error "table row '$($row.canonical)' has no command file: $canonicalFile" -ErrorAction Continue
        exit 2
    }
    foreach ($setName in $Sets) {
        $alias = $row[$setName]
        if ([string]::IsNullOrWhiteSpace($alias)) { continue }
        $expected[$alias] = New-AliasBody -Canonical $row.canonical -Alias $alias -SetName $setName
        $ownerOf[$alias] = $row.canonical
    }
}

$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
$written = 0
$drift = @()

foreach ($alias in ($expected.Keys | Sort-Object)) {
    $path = Join-Path $commandsDir "$alias.md"
    $body = $expected[$alias]
    $current = if (Test-Path -LiteralPath $path) {
        [System.IO.File]::ReadAllText($path, $utf8NoBom)
    } else { $null }

    if ($current -eq $body) { continue }

    if ($Check) {
        $drift += if ($null -eq $current) { "missing: $alias.md" } else { "stale: $alias.md" }
        continue
    }

    [System.IO.File]::WriteAllText($path, $body, $utf8NoBom)
    $written++
    Write-Host "wrote $(Get-SzaPath 'commandsDir' -Relative)/$alias.md -> /$($ownerOf[$alias])"
}

# Generated files carry alias_of:; anything else in the directory is hand-written and off limits.
$orphans = @()
foreach ($file in Get-ChildItem -LiteralPath $commandsDir -Filter '*.md' -File) {
    $name = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
    if ($expected.ContainsKey($name)) { continue }
    $head = Get-Content -LiteralPath $file.FullName -TotalCount 12 -Encoding utf8
    if ($head -match '^\s*alias_of:\s*\S') { $orphans += $name }
}

if ($orphans.Count -gt 0) {
    if ($Prune) {
        foreach ($orphan in $orphans) {
            Remove-Item -LiteralPath (Join-Path $commandsDir "$orphan.md") -Force
            Write-Host "pruned $(Get-SzaPath 'commandsDir' -Relative)/$orphan.md"
        }
    } else {
        Write-Host "orphan alias files (re-run with -Prune to remove): $($orphans -join ', ')"
    }
}

if ($Check) {
    if ($drift.Count -gt 0) {
        Write-Error "command-alias drift ($($drift.Count)): $($drift -join '; ')" -ErrorAction Continue
        exit 1
    }
    Write-Host "command aliases: in sync ($($expected.Count) files, sets: $($Sets -join ','))"
    exit 0
}

Write-Host "command aliases: $($expected.Count) expected, $written written, sets: $($Sets -join ',')"
exit 0
