#requires -Version 7.0
<#
.SYNOPSIS
    R0 - this project's single-agent queue runner. One fresh child process per ticket, order taken from
    the plan files, every run recorded.

.DESCRIPTION
    Generated by the harness scaffold (init-task-flow.ps1) from the project profile and then OWNED BY THE
    PROJECT: edit the parameter defaults below, never rewrite the loop. It depends on nothing but the
    ledger file and, when present, the queue file - no harness, no lease store, no lock, no chat - so it
    keeps working when the harness is not installed on the machine that runs it.

    R0 is the mono runner: the owner declares that nobody else works on this tree, so it makes no
    coordination call. It never claims a lease, takes a lock, waits for a sibling or checks that one is
    alive. The one start step drops what a previous run left behind (stale stop files, the directories in
    -ClearOnStart). A second runner that shares the tree is a different tool: it adds a per-ticket lease
    and a distinct agent identity, and nothing else.

    The loop: rank the open tickets, take the first one not already dropped, run ONE child for it in a
    fresh process with an empty context, re-read the ledger, record the run, rank again. A ticket that
    comes back with the status it started with is dropped for the rest of the run - the agent had no
    autonomous next step, and asking again would only burn the same context twice.

    Selection: tickets listed in the queue file first (open package ascending, `--` after the numbered
    ones, line order inside a package), then every other open ticket by priority descending, `updated`
    descending, id ascending. With no queue file it is the priority order. This runner reads no READY
    file; a project that keeps one adds its rows between the two groups.

    The child is started with an argument vector, never a command string: arguments passed as one string
    through Start-Process -ArgumentList lost three tickets in the project this runner came from.

    PERMISSIONS: the default -PermissionMode lets an unattended child edit and run anything inside this
    project. That is the owner's choice to make once per project, not a default to forget. Run ONE
    ticket attended first (-MaxTickets 1), read the run row and the ticket's status, and only then leave
    it alone with a ceiling.

.PARAMETER Prompt
    What the child is told, with `{id}` replaced by the ticket id. The default points the agent at the
    lifecycle skill for one step of one ticket. A project with its own pipeline command puts it here.

.PARAMETER ChildArgs
    The whole argument vector, replacing the one built from -Prompt, -PermissionMode and -Model. `{id}` in
    any element is replaced. An array cannot be passed through `pwsh -File`; call this script in-process
    (`& .\r0.ps1 -ChildArgs @(..)`) or edit the default.

.PARAMETER WorkStatuses
    The statuses that still have work left. Block* statuses, Verified and Archived are not in it, so a
    parked or finished ticket is never picked.

.PARAMETER ClearOnStart
    Directories whose CONTENTS are removed once at start. Pass an empty array when the project keeps none.

.PARAMETER DryRun
    Print the order and the child command and launch nothing; the start step does not run either.

.EXAMPLE
    pwsh -NoProfile -File .\r0.ps1 -DryRun
    pwsh -NoProfile -File .\r0.ps1 -MaxTickets 1 -TimeoutMinutes 30

    A stop: create the file named by -StopFile (or the same name with `-<instance>` appended). The runner
    finishes the ticket in hand, consumes the file and exits 0.

Exit codes:
  0  the loop ended normally: nothing left to pick, -MaxTickets reached, or the stop file appeared
  2  invalid invocation: the command or the ledger could not be found, or the ledger did not parse
  3  nothing ran: no open ticket at the first ranking
#>
[CmdletBinding()]
param(
    [string]   $Root           = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot {{rootRelative}})).Path,
    [string]   $Journal        = {{journal}},
    [string]   $Queue          = {{queue}},
    [string]   $RunsDir        = {{runsDir}},
    [string]   $StopFile       = {{stopFile}},
    [string]   $Instance       = 'mono',
    [string]   $Command        = 'claude',
    [string]   $Prompt         = {{prompt}},
    [ValidateSet('acceptEdits', 'auto', 'bypassPermissions', 'manual', 'dontAsk', 'plan')]
    [string]   $PermissionMode = {{permissionMode}},
    [string]   $Model          = '',
    [string[]] $ChildArgs      = @(),
    [string]   $IdRegex        = {{idRegex}},
    [string[]] $WorkStatuses   = @({{workStatuses}}),
    [string[]] $ClearOnStart   = @({{clearOnStart}}),
    [int]      $MaxTickets     = 0,
    [int]      $TimeoutMinutes = 90,
    [switch]   $DryRun
)

$ErrorActionPreference = 'Stop'
$journalPath = Join-Path $Root $Journal
$queuePath   = Join-Path $Root $Queue
$stopPaths   = @((Join-Path $Root $StopFile), (Join-Path $Root "$StopFile-$Instance"))   # shared, then this instance
$runsPath    = Join-Path $Root $RunsDir
$runFile     = Join-Path $runsPath "runs-$Instance.jsonl"

if ($ChildArgs.Count -eq 0) {
    $ChildArgs = @('-p', $Prompt, '--permission-mode', $PermissionMode)
    if ($Model) { $ChildArgs += @('--model', $Model) }
}

function Read-Ledger {
    # One record per line; a line that is not an object is a fault, not something to skip.
    if (-not (Test-Path -LiteralPath $journalPath)) { throw "ledger not found: $journalPath" }
    $records = @{}
    foreach ($line in [IO.File]::ReadAllLines($journalPath)) {
        if ([string]::IsNullOrWhiteSpace($line)) { continue }
        $r = $line | ConvertFrom-Json -ErrorAction Stop
        $records[$r.id] = $r
    }
    return $records
}

function Get-QueueOrder {
    # id -> sort key (package, line). Package heading = a line holding only a number or `--`.
    $order = @{}
    if (-not (Test-Path -LiteralPath $queuePath)) { return $order }
    $package = [int]::MaxValue; $n = 0
    foreach ($line in [IO.File]::ReadAllLines($queuePath)) {
        $t = $line.Trim()
        if ($t -eq '' -or $t.StartsWith('#') -or $t -match '^(ticket\s|current-next-release:)') { continue }
        if ($t -match '^(\d+)$') { $package = [int]$Matches[1]; continue }
        if ($t -eq '--') { $package = [int]::MaxValue - 1; continue }
        if ($t -match "^\S*?(?<id>$IdRegex)" -and -not $order.ContainsKey($Matches['id'])) {
            $order[$Matches['id']] = '{0:D10}.{1:D6}' -f $package, $n++
        }
    }
    return $order
}

function Get-Ranked {
    param($Ledger, $Dropped)
    $order = Get-QueueOrder
    $open = @($Ledger.Values | Where-Object { $WorkStatuses -contains $_.status -and $Dropped -notcontains $_.id })
    $listed = @($open | Where-Object { $order.ContainsKey($_.id) } | Sort-Object { $order[$_.id] })
    $rest = @($open | Where-Object { -not $order.ContainsKey($_.id) } |
        Sort-Object @{ Expression = { [int]$_.priority }; Descending = $true },
                    @{ Expression = { [string]$_.updated }; Descending = $true },
                    @{ Expression = { [string]$_.id }; Descending = $false })
    return @($listed + $rest)
}

try { $ledger = Read-Ledger } catch { Write-Host "r0: $($_.Exception.Message)" -ForegroundColor Red; exit 2 }

$exe = Get-Command $Command -CommandType Application -ErrorAction SilentlyContinue | Select-Object -First 1
if (-not $exe) { Write-Host "r0: command '$Command' not found" -ForegroundColor Red; exit 2 }

$ranked = Get-Ranked $ledger @()
if ($ranked.Count -eq 0) { Write-Host 'r0: no open ticket.'; exit 3 }

if ($DryRun) {
    Write-Host "r0 (dry run) - $($ranked.Count) open ticket(s), in the order they would run:"
    $ranked | ForEach-Object { Write-Host ('  {0}  {1,-12} {2}' -f $_.id, $_.status, $_.name) }
    Write-Host ("  child: {0} {1}" -f $exe.Source, ($ChildArgs -join ' '))
    exit 0
}

# The one start step. Unconditional on purpose - the declaration is that nobody holds anything, so a stop
# file found now was requested while no runner was alive and is stale.
foreach ($sp in $stopPaths | Where-Object { Test-Path -LiteralPath $_ }) {
    Write-Host "r0: a stale stop file was found and removed: $sp" -ForegroundColor Yellow
    Remove-Item -LiteralPath $sp -Force
}
foreach ($dir in $ClearOnStart) {
    $p = Join-Path $Root $dir
    if (Test-Path -LiteralPath $p) { Get-ChildItem -LiteralPath $p -Force | Remove-Item -Recurse -Force }
}
New-Item -ItemType Directory -Path $runsPath -Force | Out-Null

$dropped = [System.Collections.Generic.List[string]]::new()
$done = 0
while ($true) {
    $stop = @($stopPaths | Where-Object { Test-Path -LiteralPath $_ })
    if ($stop.Count -gt 0) {
        Write-Host 'r0: stop file found - finishing.'
        $stop | Remove-Item -Force                           # alone on the tree, so honouring consumes both
        break
    }
    if ($MaxTickets -gt 0 -and $done -ge $MaxTickets) { break }

    $ledger = Read-Ledger
    $next = @(Get-Ranked $ledger $dropped) | Select-Object -First 1
    if (-not $next) { break }

    $id = $next.id; $before = [string]$next.status
    $argv = @($ChildArgs | ForEach-Object { $_ -ireplace '\{id\}', $id })
    Write-Host ("r0: {0} [{1}] - starting child" -f $id, $before)

    $psi = [Diagnostics.ProcessStartInfo]::new($exe.Source)
    foreach ($a in $argv) { $psi.ArgumentList.Add($a) }
    $psi.UseShellExecute = $false
    $psi.WorkingDirectory = $Root
    $started = Get-Date
    $proc = [Diagnostics.Process]::Start($psi)
    $timedOut = -not $proc.WaitForExit($TimeoutMinutes * 60000)
    if ($timedOut) { $proc.Kill($true); $proc.WaitForExit() }   # the whole tree, not just the child
    $exit = if ($timedOut) { -1 } else { $proc.ExitCode }

    $after = [string]((Read-Ledger)[$id].status)
    if (-not $after) { $after = 'Archived' }                     # left the active ledger
    $moved = $after -ne $before
    $outcome = if ($timedOut) { 'timeout' } elseif ($exit -ne 0) { 'child-failed' } elseif ($moved) { 'ok' } else { 'no-progress' }

    $row = [ordered]@{
        id = $id; statusBefore = $before; statusAfter = $after; moved = $moved; outcome = $outcome
        exitCode = $exit; minutes = [int][math]::Round(((Get-Date) - $started).TotalMinutes)
        finishedAt = (Get-Date -Format 'yyyy-MM-ddTHH:mm:ss')
    }
    [IO.File]::AppendAllText($runFile, (($row | ConvertTo-Json -Compress) + "`n"))
    Write-Host ("r0: {0} {1} -> {2}  {3} (exit {4})" -f $id, $before, $after, $outcome, $exit)

    if (-not $moved) { $dropped.Add($id) }                       # no autonomous next step left
    $done++
}
exit 0
